name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sergeikuklin
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/sergeikuklin/my-scrapper:latest
          build-args: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            PROXY_URL=${{ secrets.PROXY_URL }}

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker login ghcr.io -u sergeikuklin -p ${{ secrets.REGISTRY_TOKEN }}
            docker pull ghcr.io/sergeikuklin/my-scrapper:latest
            docker stop my-scrapper
            docker system prune -f
            docker run -d --name my-scrapper -p 6000:6000 ghcr.io/sergeikuklin/my-scrapper:latest
